### ISSUE TITLE
有api接口获取最新的配置吗?

### ISSUE THREAD

**Issue by mycoco** [NgxuAnGMH/github-DNS#2]
我想在SwitchEnv里自动获取最新的ip与host映射关系,直接在应用层来使用

需要定时调用api接口,来获取相关的配置.

**Comment by NgxuAnGMH** [comment]
这只是一个本地的程序，不是对外的服务~没有api接口，但是如果你需要，可以尝试用熟悉的语言实现？

**Comment by mycoco** [comment]
但是你这个一般什么时候会更新?

**Comment by NgxuAnGMH** [comment]
每天的 6：30、13：30、23：30 更新一次，然后从 workflow 配置里面可以改。

**Comment by NgxuAnGMH** [comment]
建议 fork 到本地，或者自己用熟悉的语言实现，然后设置一个定时任务，定时获取。

**Comment by fuxichen** [comment]
> 建议 fork 到本地，或者自己用熟悉的语言实现，然后设置一个定时任务，定时获取。

能不能把数据写入到一个单独的文件提交到仓库呢，这样switchHosts就能通过github的地址自动更新了，
参考这个地址 https://github.com/maxiaof/github-hosts/blob/master/hosts
