### ISSUE TITLE
我感觉你这个方法不好

### ISSUE THREAD

**Issue by mycoco** [NgxuAnGMH/github-DNS#3]
1. 每次都要修改系统的hosts配置
2. 经常性的变化

还不如用360的DoH来解析, 或者配置hosts映射

![test0001](https://github.com/NgxuAnGMH/github-DNS/assets/13087155/69cc4e88-376e-447b-b1a6-f6b3b0bb0de9)

**Comment by NgxuAnGMH** [comment]
谢谢！我也涨知识了，感谢，我回头了解一下哈哈
